POST http://localhost:3333/upload
Content-Type: application/json

{
    "name": "1734572396852.png",
    "path": "CLICK: arquivo.png"
}

###

GET http://localhost:3333/pictures

###

PUT http://localhost:3333/pictures/1debe2b0-1e4f-4c1b-b110-f2560cb4fbc5
Content-Type: application/json

{
    "title": "teste edit",
    "about": "teste de post",
    "infos": "000000212"
}

###

DELETE  http://localhost:3333/pictures/ede38db5-53ca-4b8c-b328-31e1b2bed801