POST http://localhost:3333/pictures
Content-Type: application/json

{
    "title": "teste 1",
    "about": "teste de post",
    "infos": "000000212"
}

###

GET http://localhost:3333/pictures

###

PUT http://localhost:3333/pictures/0c7a3c32-7f91-4943-a008-8f1204f0ff3e
Content-Type: application/json

{
    "title": "teste edit",
    "about": "teste de post",
    "infos": "000000212"
}

###

DELETE  http://localhost:3333/pictures/0c7a3c32-7f91-4943-a008-8f1204f0ff3e