import type { Metadata } from "next";

import "@/styles/globals.css";
import "@/styles/art-css/art.css";

import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="art:bg:white-01 art:font-color:black-01">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
